### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by heronoh** [heronoh/BLASTr#3]
- arrumar o readme pois esta falando do Ruiniverse
- arrumar o que é testado no testthat
- criar função rpa testar e instalar os envs

**Comment by luciorq** [comment]
- [x] arrumar o readme pois esta falando do Ruiniverse
- [x] criar função para testar e instalar os envs
- [x] Remover `map_dfr()` e `future_map_dfr()`
- [x] arrumar o que é testado no testthat

Fixed README. It still needs to update the blast installation part.
Envs are automatically created as of version v0.1.2. (Apple Silicon Support is included on MacOS and Linux.)

Test coverage still needs to improve a bunch.
